basePath: /api/v1
info:
  contact: {}
  description: This is the API server for Enderchest.
  title: Enderchest API
  version: "1.0"
paths:
  /image:
    put:
      consumes:
      - multipart/form-data
      description: Uploads an image to the server
      parameters:
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      - description: Image metadata
        in: formData
        name: metadata
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image uploaded successfully
          schema:
            type: string
        "400":
          description: get form err
          schema:
            type: string
        "500":
          description: failed to save metadata
          schema:
            type: string
      summary: Upload image
  /ping:
    get:
      description: Checks if the server is alive
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Check server status
swagger: "2.0"
